name: CD Hello app

on:
  workflow_run:
    workflows:
      - "CI Hello app"
    types:
      - completed
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Update"
        required: true
      version:
        description: "Version"
        required: true
        default: "latest"
      run_id:
        description: "CI workflow run Id"
        required: false
        default: ""

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get latest tag
        id: git_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "latest_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/essential-spark
          tags: |
            type=raw,value=latest,enable=${{ github.event.workflow_run.head_branch == 'main' || github.ref == 'refs/heads/main' }}
            type=sha,format=short,prefix=
            type=raw,value=${{ inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.version != '' && inputs.version != 'latest' }}
            type=raw,value=${{ steps.git_tag.outputs.latest_tag }},enable=${{ steps.git_tag.outputs.latest_tag != '' }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /opt/essential-spark
            docker compose pull
            docker compose up -d